### ISSUE TITLE
USB-C 포트에 JTAG 핀을 추가하라

### ISSUE THREAD

**Issue by onkwon** [libmcu/development-board#1]
- SWDIO, SWCLK, SWO, NRST 핀 빼기
- ESP32 의 경우 SWD를 지원하지 않음
  - TMS(SWDIO)와 TCLK(SWCLK) + TDI, TDO 핀을 빼야함

### USB 일반
- [USB2 사양](https://www.usb.org/document-library/usb-20-specification), [USB3.1 사양](https://manuais.iessanclemente.net/images/b/bc/USB_3_1_r1.0.pdf), [USB4 사양](https://www.usb.org/document-library/usb4r-specification)
- https://www.usb.org/sites/default/files/USB_TCPCI_R2_V1p3_30122_CLEAN.pdf
- https://www.usb.org/sites/default/files/USB%20Type-C%20Spec%20R2.0%20-%20August%202019.pdf
- https://en.wikipedia.org/wiki/USB-C
- https://www.ti.com/lit/wp/slyy109b/slyy109b.pdf
### Debug Accessory Mode
- https://hackaday.com/2022/02/24/an-unbusy-usb-c-port-doubles-up-for-jtag-programming/
- https://threadreaderapp.com/thread/1495860045728395278.html
### Alternate Mode(SBU 기반)
- https://www.ti.com/lit/wp/slly021/slly021.pdf
- https://forum.contextualelectronics.com/t/debugging-through-a-usb-type-c-connector-only/4615
- https://chromium.googlesource.com/chromiumos/platform/ec/+/refs/heads/release-R67-10575.B/board/servo_micro/ccd.md
### Type-C
- https://www.embedded.com/usb-type-c-and-power-delivery-101-ports-and-connections/

**Comment by Wizmik187** [comment]
위 자료에 따르면 코어보드에 아래와 같은 OPAMP 회로, AND gate, MUX 회로가 들어가야 합니다.
![image](https://user-images.githubusercontent.com/20197999/192659547-e1d0d559-9acf-437c-a5fb-fc8ffb59fda1.png)

현실성이 좀 없다는 생각이 드네요.

**Comment by Wizmik187** [comment]
SBU1, SBU2 핀이라고, Audio accessary 를 위한 핀이 있기는 한데 이 2핀을 뺄 수는 있을 것 같아요. 검토 해보고 알려드리죠.

**Comment by onkwon** [comment]
위 자료에서도 그랬듯이 코어가 아니라 중간에 어댑터 보드를 만들어 넣어야 하지 않을까요?

**Comment by Wizmik187** [comment]
![image](https://user-images.githubusercontent.com/20197999/192660720-4b06150a-fac2-467d-94b3-62dc41102bb6.png)
요런 형태로 확인됩니다.

코어보드의 SWD 핀들을 일반적인 USB host에 연결했을 때, 영향이 없도록하기 위해서. DAP 모드에 들어갔을 때만 SWD 핀들이 USB C 핀에 연결되게 하기 위함.

**Comment by onkwon** [comment]
아, USB로부터 SWD 핀에 데미지가 갈까봐 있는거군요.

**Comment by Wizmik187** [comment]
https://forum.contextualelectronics.com/t/debugging-through-a-usb-type-c-connector-only/4615
https://www.sparkfun.com/products/retired/14746

SBU 핀을 통한 디버깅 (구글 크롬 OS에서 사용했다고 함)

**Comment by Wizmik187** [comment]
SWDIO
SWCLK
요 두핀만 빼도 디버깅 하는데 문제는 없을까요?
리셋핀이 없을 때 불편하다던가 하는..

**Comment by onkwon** [comment]
SWDIO, SWCLK, SWO, NRST 네 핀 모두 있으면 가장 좋긴하죠.

리셋은 실제로 SWD 만으로 가능한데, "connect under reset" 를 지원해야 할 경우 문제가 있을지도 모르겠어요.

그래서 최선은 4핀 모두, 차선은 SWDIO, SWCLK, SWO 3핀, 정 안되면 SWDIO, SWCLK 두핀으로 가면 좋을 것 같아요.

**Comment by onkwon** [comment]
위 자료와 USB 사양을 읽어보고 있는데요,

SuperSpeed 를 사용하지도 않고 USB4 기능을 사용하지도 않으니 호스트에서 RX 핀을 건드릴 일이 없을 것이고 그럼 SWD 핀에 데미지가 갈 일도 없을 것 같습니다. 그러니까 자료에 있는 추가 회로를 생략하고 어댑터 보드만 추가하는 방향으로 가는 것도 괜찮은 방법일 것 같습니다.

**Comment by Wizmik187** [comment]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/20197999/194855635-78c68ef3-e861-4793-b057-84ff0d797081.png">

- RX 4핀에 디버깅 핀 할당
- SBU1, 2 핀으로 어댑터보드 방향 알려주기 (LED 연결)

**Comment by onkwon** [comment]
[USB Type-C 스펙](https://www.usb.org/sites/default/files/USB%20Type-C%20Spec%20R2.0%20-%20August%202019.pdf) Appendix. B 절을 읽은 내용을 요약하면:

- Debug Accessory Mode 로 들어가려면 CC 두 핀 모두 풀업이거나 풀다운이어야 함
- 문제는 Type-C 케이블에 CC 라인이 들어가 있지 않음
- 따라서 직접 연결하거나 captive 디바이스여야 함
- 아래 그림처럼 노란색 핀은 자유롭게 사용할 수 있음
<img width="730" alt="Screen Shot 2022-10-10 at 23 02 51" src="https://user-images.githubusercontent.com/13377204/194884297-2b4124a4-ffaf-4966-9cba-2026f46be6cb.png">

그래서 제 생각을 정리하면:
- 우리는 어댑터 보드를 사용하므로 케이블 문제는 고려사항이 아님
  - 개발보드 - 어댑터보드 - PC 직접 연결하기 때문
- 위 그림의 노란색 핀을 자유롭게 사용할 수 있으므로 커넥터 방향에 자유로울 수 있도록 여분의 tx/rx 핀을 모두 활용하면 어떨까 싶어요
- 그리고 사실 개발보드와 어댑터보드는 핀을 모두 연결하더라도 어댑터보드에서 PC로 가는 핀은 데이터 핀만 연결해도 상관없잖아요?
- 이런식으로 연결해서 사용하면 될 것 같은데, 어떻게 생각하시나요? : https://www.reddit.com/r/embedded/comments/syihdl/comment/hxy10b9

**Comment by Wizmik187** [comment]
https://itecnotes.com/electrical/electronic-usb-c-debug-accessory-mode-and-usb-2-0/

**Comment by onkwon** [comment]
![adap](https://user-images.githubusercontent.com/13377204/194967056-c15fea69-9ab7-4cd2-8e2e-2b05a9186312.png)

- 우리는 그림과 같은 구성이니까 존이 공유한 링크에서 말한 우리 Core 보드(TS)는 compliant final product 가 될거고,
- 어댑터보드의 왼쪽(TS와 연결되는 쪽)은 DTS 역할로 CC 라인을 조작
- 어댑터보드의 오른쪽(PC와 연결되는 쪽)은 다시 CC 라인을 조작하지 않는 정상적인 포트로 사용하면 되지 않을까요?
  - 이 때 굳이 다른 JTAG 라인을 연결할 필요도 없을 것 같고요. 이 포트는 USB2.0 기능만 사용할테니 D+ D-만 연결해도 될 것 같아요

제가 뭔가 놓친게 있을까요?

**Comment by Wizmik187** [comment]
DTS (어댑터 보드) 에서 CC 라인 2개를 모두 Pull-up 하면 TS (코어보드) 에서 DTS 가 연결되었다는 것을 인식하고, MUX 등을 이용하여 안쓰는 USB C 커넥터 핀에 SWD 핀이 연결되도록 하는 것이 정석일것 같습니다.  (제일 처음 봤던 아래 링크 문서처럼)
(https://hackaday.com/2022/02/24/an-unbusy-usb-c-port-doubles-up-for-jtag-programming/) 

단, 이 경우엔 MUX  등의 불필요한 부품이 코어보드에 추가 되는 것이 문제이죠.

DAM 에서는 Host (PC 등)에 연결되는 상황을 정의하지는 않는 것 같아요. 사용자 몫인 것이죠.
DTS 없이 TS(코어보드) 를 바로 Host에 연결했을 때가 걱정되는 것이죠.

- MUX 등 부품을 추가하여 안전하게 간다.
- 왠만해서는 RX 핀을 안건드릴 거라고 가정하고, RX 핀에 SWD 핀을 할당한다.
- reversible 을 위하여  RX, TX 핀에 SWD  핀을 할당한다. 단 이 경우 위보다 문제가 생길 확률이 높음.

**Comment by Wizmik187** [comment]
일반적인  USB C 케이블은 CC 핀 하나가 케이블에서 풀다운 되어 있기 때문에, CC 핀 2개 모두가 풀업되는 경우는 없습니다.
DTS (어댑터 보드)에서 DAM 을 위해 CC 핀 2개를 강제로 풀업시켜서, 지금 연결되는게 DTS이다 라고 TS에게 알려주는 것이죠.

**Comment by Wizmik187** [comment]
USB 3.0 이상에서 추가되는 rx 핀이 host에 연결되지 않도록 USB 2.0 케이블만 사용하도록 가이드를 주는 방법이 가장 현실적일것 같습니다.

**Comment by Wizmik187** [comment]
아래와 같은 방법 어떠신가요.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/20197999/195360575-07774585-ab8f-46a6-8edb-4836f8de73c4.png">


<img width="346" alt="image" src="https://user-images.githubusercontent.com/20197999/195357082-d4265deb-7f7f-4499-9818-22316fefb2a2.png">


1. 아날로그 스위치 IC 를 사용하여 nRESET, SWDIO, SWO, SWCLK 4핀을 on / off 할수 있게 합니다.
2. USB C 커넥터의 SBU2 핀을 아날로그 스위치의 Control 핀에 연결하고,
3. 어댑터 보드가 꼽히면 SBU2 핀에 5V를 공급하게 해서 아날로그 스위치 IC를 on 시켜서 4핀을 연결시킵니다.

SBU1 SBU2 핀은 
https://www.usb.org/sites/default/files/USB%20Type-C%20Spec%20R2.0%20-%20August%202019.pdf 
위 링크의 아래 절 참조
- 4.3 Sideband Use (SBU)
- Table A-1 USB Type-C Analog Audio Pin Assignments

Audio Adapter Accessory Mode 에서 MIC / AGND 로 쓰이므로 host 에서 별다른 영향을 주지는 않을 것으로 보입니다.

**Comment by onkwon** [comment]
좋습니다! 말씀하신대로 하면 핀 대칭도 유지할 수 있겠네요. 👍

**Comment by onkwon** [comment]
그런데 다른 회로들을 좀 찾다보니 SWO 보다 Vref 핀을 빼는게 정석(?)인가 싶네요?

**Comment by Wizmik187** [comment]
쿤,
<img width="562" alt="image" src="https://user-images.githubusercontent.com/20197999/195642749-64d579df-288c-4f4b-b163-2f504a9bf5f8.png">

ESP32 는 JTAG는 지원하는데 SWD를 지원하지 않는다는다네요...

JTAG는 TDI, TDO, TCK, TMS 총 4핀에 reset 까지 5핀이 필요한것 같습니다..

**Comment by onkwon** [comment]
네, 이슈 description 에 업데이트 해두었었는데, 앞으로 업데이트할 때 따로 알림을 해야겠네요.

저는 커넥터 좌우 대칭을 유지하고 싶고, 스위치 IC에 여분 핀도 없으니 ESP32 의 경우는 reset 을 빼고 가면 어떨까 싶습니다.

**Comment by onkwon** [comment]
핀 아웃은 아래 이미지처럼 하면 어떨까요? 검색해보니 JLink edu mini 와 ULinkPro pinout 이 같더라고요.

![10pinout](https://c.a.segger.com/fileadmin/images/products/J-Link/Accessory/Adapters/J-Link_9-pin_Cortex-M_Adapter.png)

- https://www.segger.com/products/debug-probes/j-link/models/j-link-edu-mini/
- https://developer.arm.com/documentation/101416/0100/Hardware-Description/Target-Interfaces/Cortex-Debug--10-pin-

**Comment by onkwon** [comment]
존, 이건 정리된 것 같으니 이슈 닫을게요. 필요하시면 다시 열어주세요.
