### ISSUE TITLE
코어보드의 소자 소비전류, 정확도, 가격을 파악하라

### ISSUE THREAD

**Issue by onkwon** [libmcu/development-board#2]
- BQ25180YBGR
  - https://www.ti.com/lit/ds/symlink/bq25180.pdf
- TMP103BYFFR
- APA102-2020

**Comment by onkwon** [comment]
## BQ25180

### 사양

| FUNC | MIN | TYP | MAX | UNIT |
| ----- | ---- | ----- | ----- | ----- |
| Input Voltage | -0.3 | | 25 | V |
| Voltage | -0.3 | | 5.5 | V |
| Input Current | | | 1.1 | A |
| SYS Discharge Current | | | 1.5 | A |
| Output Sing Current | | | 20 | mA |
| VBAT | 2.2   | | 4.6   | V       |
| VIN    | 2.7    | | 5.5   | V      |
| Tj*     | -40  | | 125  | C       |
| Quiescent Current(VIN) | | 0.75 | 1 | mA |
| Quiescent Current(BAT) | | 4 | 5 | uA |

- Tj*: Operating Junction Temperature Range

### 노트
- 배터리 완전 방전을 방지하기 위해 `CHARGERCTRL1` 레지스터의 `BUVLO` 비트를 설정해야 함
- overvoltage protection 기능도 있음. 입력전압에 대한 상대값이기 때문에 디폴트 유지하기로
- `IBAT_OCP` 레지스터에 배터리 overcurrent 설정할 것
- Safety timer 를 활용하면 사용자에게 알람 줄 수 있음
  - INT 핀 MCU 에 연결했는지 확인
- Thermal protection 기능 좋아 🥹

### 할일
- [ ] 리셋핀을 MCU 에서 빼지말고 BQ25180 TS/MR 핀활용하면 어떨지
  - 다른 버튼 하나는 MCU GPIO 핀을 연결할 수 있고
  - MCU 뿐만 아니라 시스템 전체가 리셋됨
  - 소비젼류가 늘어나는 문제가 있지만, 저전력이 중요한 제품에서는 해당 기능을 끄는 방법이 있겠음
  - 또 하나의 문제는 300ms latency 가 발생하는 건데, 리셋은 보통 개발단계에서만 사용될 것이기 때문에 괜찮지 않을까 싶음
- [ ] 배터리 용량 결정하고, 충전 및 방전 시간 명시

**Comment by Wizmik187** [comment]
@onkwon 그럼 MCU 리셋 버튼이 없을텐데요? 괜찮을까요?

**Comment by onkwon** [comment]
버튼에 TS/MR 핀을 연결하고

- 300ms 이상 누르면 MCU soft reset
- 5초 이상 누르면 시스템 전체 hard reset

이렇게 가면 어떨까요?

**Comment by Wizmik187** [comment]
이해했습니다. 좋은생각인 것 같아요. 단 펌웨어 드라이버에서 버튼 컨트롤하는 부분이 들어가야할것 같습니다. 데이터시트를 좀더 읽어보고 회로 결정할게요.

**Comment by onkwon** [comment]
> [...] 펌웨어 드라이버에서 버튼 컨트롤하는 부분이 들어가야할것 같습니다. [...]

어떤 컨트롤을 말씀하시는 건가요? 아래 이미지처럼 기존 회로에서 다른 변경없이 MR 핀에 nRESET 만 엮어주면 되지 않나요?

![image](https://user-images.githubusercontent.com/13377204/196596690-82d957fa-7735-4aa5-8bc9-8b9dd35dbb9f.png)

**Comment by onkwon** [comment]
@Wizmik187 
현재 MR 핀을 어떻게 연결할지 두가지 안이 있는데요:
1. *사용자 버튼*에 연결(MCU GPIO 핀과 함께 연결)
2. *Reset 버튼*에 연결

저는 2번을 선호해요. 제 논리는 아래와 같습니다:
- *MCU 리셋* 이든 *시스템 리셋* 이든 리셋은 리셋 버튼으로 이루어져야 한다고 봄
  - 시스템 리셋을 위해 *리셋 버튼*이 아니라 *사용자 버튼*을 누른다는 게 직관적이지 않음
  - MR 핀의 시스템 리셋과 *사용자 버튼*의 custom 기능이 충돌할 수 있음
    - 이런 사용자 고려사항들은 없을수록(단순할수록) 좋다고 보임
    - 그리고 충돌을 피하기 위해 시스템 리셋의 홀드시간을 늘리는 것도 사용자 편의를 크게 감수해야 함
- *사용자 버튼*은 이미 MCU 의 GPIO 에 연결되어 있으므로 MR 핀으로 입력받은 short/long 버튼은 기능적으로 의미가 있어보이지 않음

**Comment by Wizmik187** [comment]
쿤 말 듣고, Reset 핀에 연결하는 것도 나쁘지 않을 것 같다고 설득되긴 했는데요,

Reset 버튼이나 사용자 버튼에 MR핀을 같이 연결하기에는 아래와 같은 문제가 있을 것 같습니다.
![image](https://user-images.githubusercontent.com/20197999/197489404-f0c3361e-7fbf-4edb-bb97-8d58a81aa8f7.png)

데이터시트 그림에 따르면 bq25180이 MR 핀으로 계속 pulse 를 만들고 이 펄스로 버튼 누르는 시간을 감지하고 있는 것 같습니다. 즉 Reset 핀이나 GPIO에 이 펄스가 입력되면 MCU 오동작이 예상됩니다.

따라서 일단은 GPIO와 같이 물리는건 포기하고 처음에 얘기했던것 처럼 아래와 같이 저항으로 선택할 수 있게 하는게 어떨까 해요. (default 는 GPIO 연결)
![image](https://user-images.githubusercontent.com/20197999/197492350-c28e8dc3-026b-4d5f-ad44-a9478df0eea7.png)

**Comment by onkwon** [comment]
<img width="981" alt="Screen Shot 2022-10-24 at 19 53 09" src="https://user-images.githubusercontent.com/13377204/197510700-2372dc77-6a77-4008-99b2-4edb80b6fb33.png">

타이밍 차트 표현이 헷갈리게 해놓은 것 같아요. 그런데 제가 이해하기론, 전력소비를 줄이기 위해 200ms 주기로 센싱한다는 것 같습니다. 그래서 여전히 2번을 주장해봅니다 😅

**Comment by Wizmik187** [comment]
네 쿤 말씀이 맞는 것 같습니다. 그런데 추가로 걱정되는게 생겼습니다.

일단 기본적으로 Reset 핀에는 풀업이 달려있기 때문에(ESP의 경우  autoreset을 위해 1uF Cap 도 부착) , reset 핀을 MR 핀에 연결하는 순간 MR 핀에도 풀업이 달리게 되고, 이 경우 TS (NTC 연결하여 온도 측정) 하는 기능이 제 동작을 못할 수 있습니다.

최악의 상황에는 External NTC Monitoring (TS) 기능을 disable 해야 할수도 있을것 같습니다.

요 회로는 한번 TI community에 올려서 TI 쪽에 체크를 받아볼게요.

**Comment by Wizmik187** [comment]
생각해보니 10KR풀업 저항과 10K NTC 가 달리는 순간 Reset 핀이 3.3/2 V 이 될 거고 리셋핀 동작이 제대로 안되겠네요.
reset 핀과 NTC와 같이 사용하기는 어려울것 같습니다.

쿤 말씀대로 0R 을 추가하는게 현실적이겠네요.

**Comment by onkwon** [comment]
네, 내부 온도센서가 있기 때문에 제 생각에는 외부 온도센서를 붙이는 일이 보통은 없을 것 같거든요. 그래서 그런 케이스를 그렇게 비중을 두고 고려할 필요가 있을까 싶어요. 어떻게 생각하세요?

**Comment by Wizmik187** [comment]
네 좋습니다.
짧게 누르면 MCU reset 길게 누르면 전체 하드웨어 리셋이 일관성이 있어서 좋을것 같습니다.

Ti support 에 문의했으니 회로적으로 문제 없는지 보겠습니다.

https://e2e.ti.com/support/power-management-group/power-management/f/power-management-forum/1164580/bq25180-able-to-place-pullup-resistor-to-mr-pin

**Comment by onkwon** [comment]
뒷북이긴 한데, M5Stack 에는 어떤 IC를 썼나 궁금해져서 찾아봤습니다. [AXP192](https://github.com/m5stack/M5-Schematic/blob/master/Core/AXP192%20Datasheet_v1.1_en_draft_2211.pdf) 을 사용했는데, 가격이 깡패입니다: $0.35
따로 레귤레이터가 필요하지도 않구요.

**Comment by onkwon** [comment]
정리된 내용이므로 이슈 닫겠습니다.
