### ISSUE TITLE
코어보드 사양을 결정하라

### ISSUE THREAD

**Issue by onkwon** [libmcu/development-board#4]
## MCU
- [x] ESP32
  - ESP32-WROOM-32E-N4
  - [ESP32-WROOM-32E Datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32e_esp32-wroom-32ue_datasheet_en.pdf)
  - [ESP32 Series Datasheet](https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf)
  - https://www.espressif.com/en/products/modules
  - 안테나 때문에 비용에 따라 ESP32-WROVER-IE 를 고려해보는 것도
  - 100개 기준 $2.85
    - https://lcsc.com/product-detail/WiFi-Modules_Espressif-Systems-ESP32-WROOM-32E-N4_C701341.html
- [ ] ESP32-C3
- [ ] STM32
  - STM32G0 vs STM32G4
- [x] nRF52840
- [ ] nRF9160

## 디버깅 포트
SWDIO, SWCLK 두 핀으로 플래시를 비롯한 디버깅 기능은 문제없이 사용할 수 있음. 하지만 "connect under reset"(SWD 핀을 다른 용도로 사용할 경우) 를 지원해야 할 경우 문제. 이 때는 NRST 핀이 필요함. SWO 는 플러스 옵션.

- [x] SWDIO
- [x] SWCLK
- [x] SWO
- [x] NRST

## 온도센서
대게의 경우 SoC 에 내장된 온도센서가 하나씩 있음. ESP32 에만 없음(ESP32 C3/S3 에는 있음)

## 소비전류
TBD

## PMU
- [ ] BQ25180YBGR
  - https://www.ti.com/lit/ds/symlink/bq25180.pdf
- [ ] AXP202
  - https://dl.linux-sunxi.org/AXP/AXP202%20Datasheet_v1.0_en.pdf
  - https://github.com/tuupola/axp202
- [ ] AXP192
  - https://github.com/m5stack/M5-Schematic/blob/master/Core/AXP192%20Datasheet_v1.1_en_draft_2211.pdf

## 주변장치
- [x] ADC
- [x] UART
- [x] SPI
- [x] I2C
- [x] Timer(PWM)
- [ ] USB
- [ ] DMA
- [ ] QSPI

## 핀아웃(폼팩터)
![Pin Descriptions](https://user-images.githubusercontent.com/20197999/198325717-b572a618-983e-4156-8259-81021f6312df.png)

### USB C

반대 방향과 대칭이므로 윗줄만 나타냄

| GND | TX1+ | TX1- | VBUS | CC1 | D+ | D- | SBU1 | VBUS | RX2- | RX2+ | GND |
| ----- | ----- | ----- | ----- | ----- | ---- | ---- | --- | ----- | ----- | ----- | ------ |
|          |           |          |           |           |        |          |  Target VCC  |          | SWDIO | SWCLK |    |

## ESP32 Core 보드 사양

| Name | Desc. |
| ------ | ----- |
| ESP32-WROOM-32E-N4(ESP32-D0WD-V3) | 240MHz dual core, 600 DMIPS, 520KB SRAM, Wi-Fi, BLE |
| Flash | 4MB |
| PSRAM | - |
| Input Voltage | 5V @ ?mA |
| Interface | TypeC |
| LED | Blue power indicator light |
| Button | Reset button, User button |
| PMU | BQ25180YBGR |
| USB Chip | CH9102F |
| Lithium Battery | ?mAh @ ?V |
| Antenna | 2.4GHz PCB antenna |
| Operating temperature | -40 ~ 85 (다른소자 확인필요) |
| Net Weight | |
| Gross Weight | |
| Product Size | |

**Comment by onkwon** [comment]
언급된 MCU 중에 ESP32 에만 USB 가 없습니다.
uart_to_usb 칩은 외부로 빼는 방법이 있겠지만, 다른 보드와의 호환성이나 사용자 편의를 생각하면 내장하는 게 좋을 것 같습니다.

**Comment by onkwon** [comment]
@Wizmik187 ESP32 HSPI vs VSPI 에서 저는 VSPI 핀만 뽑아도 충분할 것 같아요.

- 두개다 하드웨어 SPI 이고
- HSPI 가 JTAG 핀과 겹치기도 하고요

**Comment by onkwon** [comment]
그리고 존이 말씀하셨듯이 주변장치 핀아웃은 "가능한" 모든 보드에서 호환되는 방향으로 가면 좋을 것 같아요.

**Comment by Wizmik187** [comment]
아래 링크에 따르면 VSPI HSPI 간 속도차이가 있는 것 같고 HSPI 가 더 빠를것 같긴 한데요. 그래도 VSPI 를 빼는게 괜찮을까유?

https://www.youtube.com/watch?v=UUsP7u4vkN0&ab_channel=CoherentWave

**Comment by Wizmik187** [comment]
- USB 다이오드 추가
- 커넥터 1x8 로 2개로 변경
- 바텀면 있는 소자를 전부 탑면으로 옮길 수 있는지 검토

**Comment by onkwon** [comment]
VSPI 나 HSPI 나 기능상으로는 별다른 차이가 없어서 뭘 사용해도 상관없을 것 같은데, HSPI 가 JTAG 핀과 겹치니 VSPI 사용하면 좋을 것 같습니다.
