### ISSUE TITLE
회로를 리뷰하라

### ISSUE THREAD

**Issue by onkwon** [libmcu/development-board#8]
올려주신 회로보고 몇가지 의문사항 남겨요

## 1. 사용자 버튼은 빠지는 건가요?
공간상 넣기가 곤란하다면 스루홀? 형태로 하나 빼놓는 건 어떨까요?
## 2. 4.4v ~ 4.9v 범위의 전압을 VSYS 핀으로 내보내게 되는데 쓸모가 있을지 의문입니다
- VIN 을 넣는건 어떨까요?
- 지금은 전원 유입될 수 있는 곳이 USB 포트밖에 없어서 VIN이 있으면 활용 여지가 있을 것 같습니다 
## 3. 아래 회로에서 SYS는 output 인데 input 심볼이 있는 것 같아요
![image](https://user-images.githubusercontent.com/13377204/198519822-7138a190-ac6f-4aed-89a4-9ef6712a23d9.png)

**Comment by Wizmik187** [comment]
1.
사용자 버튼은 바텀면 중앙에 위치시켰습니다. 자리만 있고 부품 실장은 안하려고 합니다. (SMT를 탑면만 하여 비용 절감)
사용자가 필요하다면 솔더링 하여 사용하는 것으로 생각하고 있어요. 
![image](https://user-images.githubusercontent.com/20197999/198522066-d716a154-6dc3-4413-acbc-ebd91617ada5.png)

바텀면 중앙이 버튼 위치로는 자연스러워서 위와 같이 했는데, 고민중이긴 합니다. 리셋버튼이랑 대칭되게 탑면에 배치할 수는 있을것 같아요.

마찬가지로 NTC도 자리만 있고 필요하다면 솔더링 하여 사용하도록 가이드 하려고 합니다.

2.
여러가지 상황을 고려했는데요, 일단은 헤더핀으로 사용하는 센서나 기타 주변기기에 
전원을 공급해야 할때 SYS 전원을 사용할 수 있습니다. 3.3V LDO 는 최대 전류가 300mA라서 애매한 경우가 생길 수 있습니다. 3.3V 외의 다른 전압 (예를 들면 1.8V나 12V) 을 만들어야 할 때도, 3.3V 를 입력으로 넣는 것보다 SYS를 넣는 것이 더 효율적일것 같아요.

또한 외부에서 전원을 공급받을 때도, SYS핀을 통해 공급받는 것이 각종 bq25180 Safety feature 를 사용할 수 있을거라는 생각이 들어요. 
![image](https://user-images.githubusercontent.com/20197999/198523626-3db31f8a-213d-4cc0-a2bd-9feae2afb316.png)
위와 같이 세팅하면, VIN (USB 전원)이 존재해도 쫑안나고 안전하게 SYS핀을 통해 전원을 공급받을 수 있을듯 합니다. 
(SYS 핀으로 전원을 공급하고 싶을 때는 SYS off floating 으로 세팅하도록 가이드) 

3.
수정하였습니다!

**Comment by onkwon** [comment]
## 1
- 저도 의견을 보태자면, 버튼은 탑면에 배치하고 실장하면 좋을 것 같습니다
- 그리고 배터리를 부착하게 되면 위치가 아마도 현재의 사용자 버튼 위치가 되지 않을까요?
- 그런 점에서 NTC 위치도 구석으로 좀 밀면 어떨까 싶기도 하고요

## 2
좋습니다. 👍 `SYS` 핀에 그런 기능이 있는지 몰랐네요. 하나 추가적으로 드는 의문이

- `SYS_MODE` 가 `00` 인 상태(Normal Operation)에서 SYS 로만 전원이 공급되는 경우에는 문제가 없을 것 같은데
- `SYS_MODE` 가 `00` 인 상태(Normal Operation)에서 IN 으로도 전원이 공급되고 SYS 로도 전원이 공급되는 경우에는 어떻게 동작하게 될까요?

왜냐하면 상시전원 제품이라고 가정하고, 전원을 넣은 상태에서 디버깅을 위해 USB 를 꽂아도 괜찮을까 라는 생각이 들었어요.

## spec.
spec. 정리를 위해 아는 것만 요약해보면

### 전원
- IN 입력 전압은 2.7 ~ 5.5VDC(최대값은 -0.3 ~ 25VDC)
- IN 최대 허용 전류는 1.1A
- [출력] SYS 최대 허용 전류는 1.5A
  - 순간(<20ms) 최대 허용 전류는 2.5A
- [입력] SYS 최대 입력 전압은 1.8 ~ 5.5VDC

### 온도
| 소자 | 온도(도섭씨) |
| ---- | ----------- |
| TCR3RM33A | -40 ~ 85 |
| BQ25180 | -40 ~ 125 |
| SN74LV4066ARGYR | -40 ~ 85 |
| CP2102N | -40 ~ 85 |
| KUSBX-SMT-CS2-B30TR | -30 ~ 85 |
|  ESP32-WROOM-32E | -40 ~ 85 |

PCB, 커넥터, 패턴등이 어떻게 되는지 모르지만, 일단은 권장 온도는 -30 ~ 85 도 라고 볼 수 있겠네요.

**Comment by Wizmik187** [comment]
> * `SYS_MODE` 가 `00` 인 상태(Normal Operation)에서 SYS 로만 전원이 공급되는 경우에는 문제가 없을 것 같은데
> * `SYS_MODE` 가 `00` 인 상태(Normal Operation)에서 IN 으로도 전원이 공급되고 SYS 로도 전원이 공급되는 경우에는 어떻게 동작하게 될까요?

사실 이부분은 저도 추측으로 괜찮을 거 같다 라고 생각만 드는거라서, 정확히는 이렇게 사용해도 되는지 TI 쪽에 문의를 해보겠습니다.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/20197999/199022093-1f1f5a9b-bb90-4104-b8c1-d4b410eae9a7.png">

일단 제 판단에는, FET로 전류제어하는 기능이 있기 때문에, SYS에 전원이 있는 상태에서 IN에 5V가 들어와도 어느 한쪽으로 스펙이상의 전류가 흘러서 IC가 망가지거나 하는 일은 없을 것 같긴 합니다.

**Comment by onkwon** [comment]
더이상 관련 이슈가 없으므로 닫겠습니다.
